Repository GNDVMall/GNDV-back, pull requests merged in 2024-06, with the labels that each got.

#49 Feat: 채팅방 api 작업 #42
  src/main/java/com/gndv/chat/controller/ChatController.java
  src/main/java/com/gndv/chat/domain/dto/request/ChatRoomCreateRequest.java
  src/main/java/com/gndv/chat/domain/dto/response/ChatRoomDetailResponse.java
  src/main/java/com/gndv/chat/domain/dto/response/ChatRoomListResponse.java
  src/main/java/com/gndv/chat/domain/dto/response/ChatRoomResponse.java
  src/main/java/com/gndv/chat/domain/entity/ChatMessage.java
  src/main/java/com/gndv/chat/domain/entity/ChatRoom.java
  src/main/java/com/gndv/chat/domain/entity/ChatRoomDetail.java
  src/main/java/com/gndv/chat/domain/entity/ChatUser.java
  src/main/java/com/gndv/chat/mapper/ChatMapper.java
  src/main/java/com/gndv/chat/service/ChatService.java
  src/main/java/com/gndv/constant/ChatUserType.java
  src/main/java/com/gndv/image/controller/ImageController.java
  src/main/java/com/gndv/item/controller/ItemController.java
  src/main/java/com/gndv/product/controller/ProductController.java
  src/main/java/com/gndv/product/domain/dto/request/ProductInsertRequest.java
  src/main/java/com/gndv/product/domain/dto/request/ProductUpdateRequest.java
  src/main/java/com/gndv/product/mapper/ProductMapper.java
  src/main/java/com/gndv/product/service/ProductService.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
Labels: feat

#53 fix: 누락된 시큐리티 코드 추가
  src/main/java/com/gndv/security/configs/SecurityConfig.java
Labels: bug

#56 fix(JWTToken)
  build.gradle
  src/main/java/com/gndv/member/controller/LoginController.java
  src/main/java/com/gndv/member/controller/MemberController.java
  src/main/java/com/gndv/member/domain/entity/Member.java
  src/main/java/com/gndv/security/configs/AuthConfig.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
  src/main/java/com/gndv/security/dsl/RestApiDsl.java
  src/main/java/com/gndv/security/entrypoint/RestAuthenticationEntryPoint.java
  src/main/java/com/gndv/security/filters/JWTAuthenticationFilter.java
  src/main/java/com/gndv/security/filters/RestAuthenticationFilter.java
  src/main/java/com/gndv/security/handler/FormAccessDeniedHandler.java
  src/main/java/com/gndv/security/handler/FormAuthenticationFailureHandler.java
  src/main/java/com/gndv/security/handler/FormAuthenticationSuccessHandler.java
  src/main/java/com/gndv/security/handler/JwtAuthenticationSuccessHandler.java
  src/main/java/com/gndv/security/handler/RestAccessDeniedHandler.java
  src/main/java/com/gndv/security/handler/RestAuthenticationFailureHandler.java
  src/main/java/com/gndv/security/handler/RestAuthenticationSuccessHandler.java
  src/main/java/com/gndv/security/provider/FormAuthenticationProvider.java
  src/main/java/com/gndv/security/service/FormUserDetailsService.java
  src/main/java/com/gndv/security/service/JwtService.java
  src/main/resources/application.properties
Labels: enhancement

#57 feat: payment 검증기능까지 완성
  src/main/java/com/gndv/payment/controller/OrderController.java
  src/main/java/com/gndv/payment/controller/PaymentController.java
  src/main/java/com/gndv/payment/domain/dto/LocalPayRequest.java
  src/main/java/com/gndv/payment/domain/entity/LocalPayment.java
  src/main/java/com/gndv/payment/domain/entity/OrderList.java
  src/main/java/com/gndv/payment/mapper/OrderMapper.java
  src/main/java/com/gndv/payment/mapper/PaymentMapper.java
  src/main/java/com/gndv/payment/service/OrderServiceImpl.java
  src/main/java/com/gndv/payment/service/PaymentService.java
  src/main/java/com/gndv/payment/service/PaymentServiceImpl.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
Labels: enhancement

#58 Feat: CORS 설정 변경 & 일부 변경된 API
  src/main/java/com/gndv/chat/controller/ChatController.java
  src/main/java/com/gndv/chat/domain/dto/request/ChatRoomCheckRequest.java
  src/main/java/com/gndv/chat/mapper/ChatMapper.java
  src/main/java/com/gndv/chat/service/ChatService.java
  src/main/java/com/gndv/common/domain/request/PagingRequest.java
  src/main/java/com/gndv/common/domain/response/PageResponse.java
  src/main/java/com/gndv/item/domain/dto/response/ItemDetailResponse.java
  src/main/java/com/gndv/item/mapper/ItemMapper.java
  src/main/java/com/gndv/product/controller/ProductController.java
  src/main/java/com/gndv/product/domain/dto/request/ProductListPagingRequest.java
  src/main/java/com/gndv/product/domain/dto/response/ProductDetailResponse.java
  src/main/java/com/gndv/product/domain/entity/Product.java
  src/main/java/com/gndv/product/domain/entity/ProductDetail.java
  src/main/java/com/gndv/product/mapper/ProductMapper.java
  src/main/java/com/gndv/product/service/ProductService.java
  src/main/java/com/gndv/security/configs/CorsConfig.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
Labels: bug, enhancement

#59 feat: wish list api 구현
  src/main/java/com/gndv/security/configs/SecurityConfig.java
  src/main/java/com/gndv/wish/controller/WishController.java
  src/main/java/com/gndv/wish/domain/dto/WishDTO.java
  src/main/java/com/gndv/wish/domain/entity/Wish.java
  src/main/java/com/gndv/wish/mapper/WishMapper.java
  src/main/java/com/gndv/wish/service/WishService.java
  src/main/java/com/gndv/wish/service/WishServiceImpl.java
Labels: feat

#62 conflct 해결해야함
  src/main/java/com/gndv/payment/controller/OrderController.java
  src/main/java/com/gndv/payment/domain/dto/OrderResponseDTO.java
  src/main/java/com/gndv/payment/domain/entity/OrderList.java
  src/main/java/com/gndv/payment/domain/entity/Orders.java
  src/main/java/com/gndv/payment/mapper/OrderMapper.java
  src/main/java/com/gndv/payment/service/OrderService.java
  src/main/java/com/gndv/payment/service/OrderServiceImpl.java
  src/main/java/com/gndv/product/domain/dto/request/ProductInsertWithMemberRequest.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
  src/main/java/com/gndv/wish/controller/WishController.java
  src/main/java/com/gndv/wish/service/WishService.java
  src/main/java/com/gndv/wish/service/WishServiceImpl.java
Labels: enhancement, help wanted

#63 feat: soldout 기능 탑재
  src/main/java/com/gndv/payment/constain/PaymentStatus.java
  src/main/java/com/gndv/payment/controller/OrderController.java
  src/main/java/com/gndv/payment/domain/entity/Orders.java
  src/main/java/com/gndv/payment/mapper/OrderMapper.java
  src/main/java/com/gndv/payment/service/OrderService.java
  src/main/java/com/gndv/payment/service/OrderServiceImpl.java
  src/main/java/com/gndv/payment/service/PaymentService.java
  src/main/java/com/gndv/payment/service/PaymentServiceImpl.java
Labels: enhancement

#64 Feat: 채팅 api
  build.gradle
  src/main/java/com/gndv/chat/controller/ChatController.java
  src/main/java/com/gndv/chat/controller/ChatWebSocketController.java
  src/main/java/com/gndv/chat/domain/dto/request/ChatMessageRequest.java
  src/main/java/com/gndv/chat/domain/dto/response/ChatAlarmResponse.java
  src/main/java/com/gndv/chat/domain/dto/response/ChatMessageResponse.java
  src/main/java/com/gndv/chat/domain/dto/response/ChatRoomDetailResponse.java
  src/main/java/com/gndv/chat/domain/dto/response/ChatRoomResponse.java
  src/main/java/com/gndv/chat/domain/entity/ChatRoomDetail.java
  src/main/java/com/gndv/chat/handler/JwtHandshakeInterceptor.java
  src/main/java/com/gndv/chat/mapper/ChatMapper.java
  src/main/java/com/gndv/chat/mapper/ChatSocketMapper.java
  src/main/java/com/gndv/chat/service/ChatService.java
  src/main/java/com/gndv/chat/service/ChatSocketService.java
  src/main/java/com/gndv/config/WebSocketConfig.java
  src/main/java/com/gndv/constant/ProductSalesStatus.java
  src/main/java/com/gndv/product/controller/ProductController.java
  src/main/java/com/gndv/product/domain/dto/request/ProductInsertRequest.java
  src/main/java/com/gndv/product/domain/dto/request/ProductUpdateRequest.java
  src/main/java/com/gndv/product/mapper/ProductMapper.java
  src/main/java/com/gndv/product/mapper/SqlBuilder.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
  src/main/java/com/gndv/security/filters/JWTAuthenticationFilter.java
  src/main/java/com/gndv/security/handler/JwtAuthenticationSuccessHandler.java
Labels: enhancement

#66 Feat/websocket ayo
  src/main/java/com/gndv/chat/controller/ChatController.java
  src/main/java/com/gndv/chat/controller/ChatWebSocketController.java
  src/main/java/com/gndv/chat/domain/dto/request/ChatMessageRequest.java
  src/main/java/com/gndv/chat/domain/dto/response/ChatMessageResponse.java
  src/main/java/com/gndv/chat/domain/entity/ChatMessage.java
  src/main/java/com/gndv/chat/mapper/ChatMapper.java
  src/main/java/com/gndv/chat/mapper/ChatSocketMapper.java
  src/main/java/com/gndv/constant/ChatMessageUserType.java
  src/main/java/com/gndv/security/filters/JWTAuthenticationFilter.java
Labels: enhancement

#67 feat: 리뷰기능 api
  src/main/java/com/gndv/member/controller/LoginController.java
  src/main/java/com/gndv/review/controller/ReviewController.java
  src/main/java/com/gndv/review/domain/dto/request/ReviewInsertRequest.java
  src/main/java/com/gndv/review/domain/dto/response/ReviewDetailResponse.java
  src/main/java/com/gndv/review/domain/entity/Review.java
  src/main/java/com/gndv/review/mapper/ReviewMapper.java
  src/main/java/com/gndv/review/service/ReviewService.java
  src/main/java/com/gndv/review/service/ReviewServiceImpl.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
  src/main/java/com/gndv/security/filters/JWTAuthenticationFilter.java
  src/main/java/com/gndv/security/handler/JwtAuthenticationSuccessHandler.java
  src/main/java/com/gndv/security/service/JwtService.java
Labels: enhancement

#68 Feat/member imhungry2
  build.gradle
  src/main/java/com/gndv/GndvApplication.java
  src/main/java/com/gndv/configs/AppConfig.java
  src/main/java/com/gndv/configs/CloudConfig.java
  src/main/java/com/gndv/configs/WebSocketConfig.java
  src/main/java/com/gndv/member/controller/LoginController.java
  src/main/java/com/gndv/member/controller/MemberController.java
  src/main/java/com/gndv/member/domain/dto/MemberContext.java
  src/main/java/com/gndv/member/domain/dto/MemberDTO.java
  src/main/java/com/gndv/member/domain/dto/request/EditRequest.java
  src/main/java/com/gndv/member/domain/dto/request/JoinRequest.java
  src/main/java/com/gndv/member/domain/dto/request/LoginRequest.java
  src/main/java/com/gndv/member/domain/entity/Member.java
  src/main/java/com/gndv/member/mapper/MemberMapper.java
  src/main/java/com/gndv/member/service/MemberService.java
  src/main/java/com/gndv/security/configs/AuthConfig.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
  src/main/java/com/gndv/security/filters/TokenAuthenticationFilter.java
  src/main/java/com/gndv/security/handler/RestAuthenticationSuccessHandler.java
  src/main/java/com/gndv/security/handler/TokenAccessDeniedHandler.java
  src/main/java/com/gndv/security/handler/TokenAuthenticationFailureHandler.java
  src/main/java/com/gndv/security/handler/TokenAuthenticationSuccessHandler.java
  src/main/java/com/gndv/security/service/CustomUserDetailsService.java
  src/main/java/com/gndv/security/token/TokenProvider.java
  src/main/resources/application.properties
Labels: enhancement

#69 fix: 인증 관련 코드 변경으로 인해 누락된 코드와 변경된 코드들 정리
  build.gradle
  src/main/java/com/gndv/chat/handler/JwtHandshakeInterceptor.java
  src/main/java/com/gndv/common/domain/request/PagingRequest.java
  src/main/java/com/gndv/security/filters/TokenAuthenticationFilter.java
  src/main/java/com/gndv/security/handler/TokenAuthenticationSuccessHandler.java
Labels: bug

#72 Feat/search imhungry2
  src/main/java/com/gndv/configs/WebSocketConfig.java
  src/main/java/com/gndv/item/mapper/ItemMapper.java
  src/main/java/com/gndv/search/controller/CodeController.java
  src/main/java/com/gndv/search/controller/SearchController.java
  src/main/java/com/gndv/search/domain/entity/Code.java
  src/main/java/com/gndv/search/domain/entity/Search.java
  src/main/java/com/gndv/search/domain/entity/SearchInput.java
  src/main/java/com/gndv/search/domain/entity/SearchMap.java
  src/main/java/com/gndv/search/mapper/CodeMapper.java
  src/main/java/com/gndv/search/mapper/SearchMapper.java
  src/main/java/com/gndv/search/service/CodeService.java
  src/main/java/com/gndv/search/service/SearchService.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
Labels: enhancement

#73 Feat: 프로덕트 수정, 생성 시 이미지 처리 기능 추가
  src/main/java/com/gndv/image/domain/dto/ImageRequest.java
  src/main/java/com/gndv/image/mapper/ImageMapper.java
  src/main/java/com/gndv/image/service/ImageService.java
  src/main/java/com/gndv/product/controller/ProductController.java
  src/main/java/com/gndv/product/domain/dto/request/ProductInsertRequest.java
  src/main/java/com/gndv/product/domain/dto/request/ProductUpdateRequest.java
  src/main/java/com/gndv/product/mapper/ProductMapper.java
  src/main/java/com/gndv/product/service/ProductService.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
  src/main/java/com/gndv/security/handler/TokenAuthenticationSuccessHandler.java
Labels: enhancement

#75 Feat/search imhungry2
  src/main/java/com/gndv/search/controller/SearchController.java
  src/main/java/com/gndv/search/domain/request/SearchItemRequest.java
  src/main/java/com/gndv/search/mapper/SearchMapper.java
  src/main/java/com/gndv/search/service/SearchService.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
Labels: enhancement

#74 중간저장
  src/main/java/com/gndv/payment/controller/OrderController.java
  src/main/java/com/gndv/payment/domain/dto/OrderResponseDTO.java
  src/main/java/com/gndv/payment/domain/entity/Orders.java
  src/main/java/com/gndv/payment/mapper/OrderMapper.java
  src/main/java/com/gndv/payment/service/OrderService.java
  src/main/java/com/gndv/payment/service/OrderServiceImpl.java
  src/main/java/com/gndv/review/controller/ReviewController.java
  src/main/java/com/gndv/review/service/ReviewAlreadyExistsException.java
  src/main/java/com/gndv/review/service/ReviewServiceImpl.java
  src/main/java/com/gndv/security/handler/TokenAuthenticationSuccessHandler.java
Labels: enhancement

#78 feat: Item의 관심 상품 count 값을 가져오도록 쿼리 변경
  src/main/java/com/gndv/item/domain/dto/response/ItemDetailResponse.java
  src/main/java/com/gndv/item/mapper/ItemMapper.java
Labels: enhancement

#79 feat: 채팅 메시지에 타입을 추가
  src/main/java/com/gndv/chat/controller/ChatWebSocketController.java
  src/main/java/com/gndv/chat/domain/dto/request/ChatMessageRequest.java
  src/main/java/com/gndv/chat/domain/dto/response/ChatMessageResponse.java
  src/main/java/com/gndv/chat/domain/entity/ChatMessage.java
  src/main/java/com/gndv/chat/mapper/ChatSocketMapper.java
Labels: enhancement

#80 feat : 리뷰기능
  src/main/java/com/gndv/payment/controller/OrderController.java
  src/main/java/com/gndv/review/controller/ReviewController.java
  src/main/java/com/gndv/review/domain/dto/request/ReviewInsertRequest.java
  src/main/java/com/gndv/review/mapper/ReviewMapper.java
  src/main/java/com/gndv/review/service/ReviewServiceImpl.java
Labels: enhancement

#81 fix: MemberWithProfile view를 전부 Member로 변경
  src/main/java/com/gndv/chat/mapper/ChatMapper.java
  src/main/java/com/gndv/product/mapper/ProductMapper.java
Labels: bug

#82 Feat/member imhungry2
  build.gradle
  src/main/java/com/gndv/configs/EmailConfig.java
  src/main/java/com/gndv/configs/RedisConfig.java
  src/main/java/com/gndv/configs/SmsConfig.java
  src/main/java/com/gndv/constant/Status.java
  src/main/java/com/gndv/member/controller/LoginController.java
  src/main/java/com/gndv/member/controller/MemberController.java
  src/main/java/com/gndv/member/domain/dto/MemberDTO.java
  src/main/java/com/gndv/member/domain/dto/request/SmsRequest.java
  src/main/java/com/gndv/member/domain/entity/Member.java
  src/main/java/com/gndv/member/mapper/MemberMapper.java
  src/main/java/com/gndv/member/service/EmailService.java
  src/main/java/com/gndv/member/service/MemberService.java
  src/main/java/com/gndv/member/service/SmsService.java
  src/main/resources/application.properties
Labels: enhancement

#83 feat: 서버에 올린 redis와 연동
  src/main/java/com/gndv/configs/RedisConfig.java
  src/main/resources/application.properties
Labels: enhancement

#84 Feat/search imhungry2
  src/main/java/com/gndv/common/domain/request/PagingRequest.java
  src/main/java/com/gndv/common/domain/response/PageResponse.java
  src/main/java/com/gndv/search/controller/CodeController.java
  src/main/java/com/gndv/search/controller/SearchController.java
  src/main/java/com/gndv/search/domain/entity/Code.java
  src/main/java/com/gndv/search/domain/entity/Theme.java
  src/main/java/com/gndv/search/domain/request/SearchItemRequest.java
  src/main/java/com/gndv/search/mapper/CodeMapper.java
  src/main/java/com/gndv/search/mapper/SearchMapper.java
  src/main/java/com/gndv/search/mapper/ThemeMapper.java
  src/main/java/com/gndv/search/provider/SearchProvider.java
  src/main/java/com/gndv/search/service/CodeService.java
  src/main/java/com/gndv/search/service/SearchService.java
Labels: enhancement

#86 fix: 잘못된 Item get 쿼리 수정
  src/main/java/com/gndv/item/mapper/ItemMapper.java
Labels: bug

#87 feat : 프로필 기능
  src/main/java/com/gndv/member/controller/MemberController.java
  src/main/java/com/gndv/member/service/MemberService.java
Labels: enhancement

#88 Feat/member imhungry2
  src/main/java/com/gndv/configs/RedisConfig.java
  src/main/java/com/gndv/member/controller/MemberController.java
  src/main/java/com/gndv/member/domain/dto/request/ProfileRequest.java
  src/main/java/com/gndv/member/mapper/MemberMapper.java
  src/main/java/com/gndv/member/service/MemberService.java
  src/main/java/com/gndv/review/domain/entity/Review.java
  src/main/java/com/gndv/review/mapper/ReviewMapper.java
  src/main/java/com/gndv/review/service/ReviewServiceImpl.java
Labels: enhancement

#89 feat: 로그인 인포
  src/main/java/com/gndv/member/controller/MemberController.java
  src/main/java/com/gndv/member/service/MemberService.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
  src/main/java/com/gndv/wish/controller/WishController.java
  src/main/java/com/gndv/wish/service/WishServiceImpl.java
Labels: enhancement

#91 Feat/search imhungry2
  src/main/java/com/gndv/member/mapper/MemberMapper.java
  src/main/java/com/gndv/search/controller/SearchController.java
  src/main/java/com/gndv/search/domain/entity/SearchInput.java
  src/main/java/com/gndv/search/mapper/SearchMapper.java
  src/main/java/com/gndv/search/service/SearchService.java
Labels: enhancement

#93 Feat/member imhungry2
  src/main/java/com/gndv/member/domain/dto/request/ProfileDetailsRequest.java
  src/main/java/com/gndv/member/domain/dto/request/ProfileRequest.java
  src/main/java/com/gndv/member/mapper/MemberMapper.java
  src/main/java/com/gndv/member/service/MemberService.java
Labels: enhancement

#94 Feat/search imhungry2
  src/main/java/com/gndv/search/controller/SearchController.java
  src/main/java/com/gndv/search/service/SearchService.java
Labels: bug

#95 fix/member imhungry2
  src/main/java/com/gndv/member/controller/MemberController.java
  src/main/java/com/gndv/member/domain/dto/request/ProfileRequest.java
  src/main/java/com/gndv/member/mapper/MemberMapper.java
  src/main/java/com/gndv/member/service/MemberService.java
  src/main/java/com/gndv/review/mapper/ReviewMapper.java
  src/main/java/com/gndv/security/handler/TokenAuthenticationSuccessHandler.java
Labels: bug

#96 Feat/themes ayo
  src/main/java/com/gndv/search/domain/entity/Theme.java
  src/main/java/com/gndv/search/mapper/ThemeMapper.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
Labels: enhancement

#97 Feat/common imhungry2
  build.gradle
  src/main/java/com/gndv/GndvApplication.java
  src/main/java/com/gndv/common/CustomResponse.java
  src/main/java/com/gndv/common/exception/CustomException.java
  src/main/java/com/gndv/common/exception/GlobalExceptionHandler.java
  src/main/java/com/gndv/common/exception/aspect/LoggingAspect.java
Labels: enhancement

#98 fix: Item 테이블 변경으로 인한 컬럼 추가
  src/main/java/com/gndv/item/domain/dto/response/ItemDetailResponse.java
  src/main/java/com/gndv/item/domain/entity/Item.java
  src/main/java/com/gndv/item/mapper/ItemMapper.java
Labels: bug

#99 feat: Product 상태 변경 기능 추가
  src/main/java/com/gndv/product/controller/ProductController.java
  src/main/java/com/gndv/product/service/ProductService.java
Labels: bug

#100 feat: Product 상태 필드 추가
  src/main/java/com/gndv/product/domain/entity/Product.java
Labels: bug

#101 Feat/member imhungry2
  src/main/java/com/gndv/member/controller/LoginController.java
  src/main/java/com/gndv/member/controller/MemberController.java
  src/main/java/com/gndv/member/mapper/MemberMapper.java
  src/main/java/com/gndv/member/service/MemberService.java
Labels: bug

#102 검색 키워드 버그 수정
  src/main/java/com/gndv/search/controller/SearchController.java
  src/main/java/com/gndv/search/mapper/SearchMapper.java
  src/main/java/com/gndv/search/service/SearchService.java
Labels: bug

#103 feat : recent-product
  src/main/java/com/gndv/member/controller/MemberController.java
  src/main/java/com/gndv/product/controller/RecentProductController.java
  src/main/java/com/gndv/security/configs/SecurityConfig.java
Labels: enhancement

#104 Feat/member imhungry2
  src/main/java/com/gndv/member/controller/MemberController.java
  src/main/java/com/gndv/member/domain/dto/MemberDTO.java
  src/main/java/com/gndv/member/domain/dto/request/JoinRequest.java
  src/main/java/com/gndv/member/mapper/MemberMapper.java
  src/main/java/com/gndv/member/service/MemberService.java
Labels: bug

#105 feat(Swagger)
  build.gradle
  src/main/java/com/gndv/GndvApplication.java
  src/main/java/com/gndv/chat/controller/ChatController.java
  src/main/java/com/gndv/chat/controller/ChatWebSocketController.java
  src/main/java/com/gndv/configs/SwaggerConfig.java
  src/main/java/com/gndv/image/controller/ImageController.java
  src/main/java/com/gndv/item/controller/ItemController.java
  src/main/java/com/gndv/member/controller/LoginController.java
  src/main/java/com/gndv/member/controller/MemberController.java
  src/main/java/com/gndv/payment/controller/OrderController.java
  src/main/java/com/gndv/payment/controller/PaymentController.java
  src/main/java/com/gndv/product/controller/ProductController.java
  src/main/java/com/gndv/product/controller/RecentProductController.java
  src/main/java/com/gndv/review/controller/ReviewController.java
  src/main/java/com/gndv/search/controller/SearchController.java
  src/main/java/com/gndv/wish/controller/WishController.java
  src/main/resources/application.properties
Labels: enhancement

#107 Refactor/뷰카운트 ayo
  src/main/java/com/gndv/product/mapper/ProductMapper.java
  src/main/java/com/gndv/product/service/ProductService.java
  제목 없는 다이어그램.drawio
Labels: enhancement

#108 refactor: 채팅방 목록에서 닉네임, 시간, 프로필 이미지도 바뀌도록 변경
  src/main/java/com/gndv/chat/domain/dto/response/ChatRoomResponse.java
  src/main/java/com/gndv/chat/mapper/ChatMapper.java
Labels: refactor

#109 feat: 채팅방 메시지 타입 처리
  src/main/java/com/gndv/chat/domain/dto/response/ChatRoomResponse.java
  src/main/java/com/gndv/chat/mapper/ChatMapper.java
  src/main/java/com/gndv/constant/MessageUserType.java
Labels: enhancement
